### PR TITLE
PP-4 (Create nav and headerW/h1)

### PR DESCRIPTION
**Pull request by Ilona-front-end**

### CODE REVIEW

**Comment by Ilona-front-end** [comment]
tried changing branch to be able to commit to qa branch but button for add pull request was disabled

**Comment by baresi687** [comment]
package-lock.json is changed? 
@Matsfjeldstad

**Comment by baresi687** [comment]
Nice. Approved.
Wait until @Matsfjeldstad reviews before merging to QA

**Comment by Ilona-front-end** [comment]
Good notice. I can not understand why package.lock.json changed. But after I forked and then cloned repo maybe file changed after I ran "npm i", "npm run build" commands. Now I have manually added back what was deleted to package.lock.json

**Review by baresi687 — APPROVED** [review]

**Review by CarlLinusHedlund — APPROVED** [review]
Looks good! :)

**Pull request merged**
